### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by jawoll14** [LeeKamentsky/python-javabridge#143]
Hi, I am currently trying to use the microscoper wrapper and am having issues with javabridge.  When I try to use the command microscoper, I receive the following error.  I am currently running python 3 as well as java 1.8.  I have tried completely uninstalling python and then reinstalling it.  I have also tried this several times with javabridge.  When I install javabridge it informs the requirement is already satisfied via numpy with javabridge version 1.14.3.  I was wondering if you had any suggestions for how to solve this problem?  Thanks

Traceback (most recent call last):
  File "/anaconda3/bin/microscoper", line 11, in <module>
    load_entry_point('microscoper', 'console_scripts', 'microscoper')()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/jared/microscoper/microscoper/__init__.py", line 1, in <module>
    from .io import run
  File "/Users/jared/microscoper/microscoper/io.py", line 13, in <module>
    import bioformats as bf
  File "/anaconda3/lib/python3.6/site-packages/bioformats/__init__.py", line 21, in <module>
    import javabridge
  File "/Users/jared/python-javabridge/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/Users/jared/python-javabridge/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: dlopen(/Users/jared/python-javabridge/javabridge/_javabridge.cpython-36m-darwin.so, 2): Symbol not found: _kCFAllocatorDefault
  Referenced from: /Users/jared/python-javabridge/javabridge/_javabridge.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/jared/python-javabridge/javabridge/_javabridge.cpython-36m-darwin.so

**Comment by LeeKamentsky** [comment]
I'm a little confused about how your virtual environment is working. It looks like you are using Anaconda's Python, but have installed microscoper and Javabridge from source? I would create a virtual environment using "conda env create", activate that environment and then try `pip install microscoper`. I would also make sure that you do not have the PYTHONPATH environment variable installed. Hope that helps.

**Comment by jawoll14** [comment]
Hi, thanks for getting back to me.  I uninstalled Anaconda from my computer and reinstalled python3.7 onto my computer and I still received the same error.  I also created the environment (microscoper) to run the microscoper wrapper in, but yet again received the error.  I am still very new to coding, so I don't completely understand how the PYTHONPATH variable works, but when I type 'echo $PYTHONPATH', this is what I get, the output does not describe a path.
(microscoper) Jareds-MacBook-Pro-2:~ jared$ echo $PYTHONPATH


This is the error code i receive trying to run microscoper inside of the environment.
(microscoper) Jareds-MacBook-Pro-2:~ jared$ microscoper
Traceback (most recent call last):
  File "/Users/jared/miniconda3/bin/microscoper", line 11, in <module>
    load_entry_point('microscoper', 'console_scripts', 'microscoper')()
  File "/Users/jared/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/jared/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/Users/jared/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/Users/jared/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/jared/microscoper/microscoper/__init__.py", line 1, in <module>
    from .io import run
  File "/Users/jared/microscoper/microscoper/io.py", line 13, in <module>
    import bioformats as bf
  File "/Users/jared/miniconda3/lib/python3.6/site-packages/bioformats/__init__.py", line 21, in <module>
    import javabridge
  File "/Users/jared/miniconda3/lib/python3.6/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/Users/jared/miniconda3/lib/python3.6/site-packages/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: dlopen(/Users/jared/miniconda3/lib/python3.6/site-packages/javabridge/_javabridge.cpython-36m-darwin.so, 2): Symbol not found: _kCFAllocatorDefault
  Referenced from: /Users/jared/miniconda3/lib/python3.6/site-packages/javabridge/_javabridge.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/jared/miniconda3/lib/python3.6/site-packages/javabridge/_javabridge.cpython-36m-darwin.so


Also, I was wondering if you could explain why it would be an issue that I used Anaconda's Python, but installed microscoper and javabridge from source or recommend someplace where I could learn more about stuff like this?  Thanks

**Comment by LeeKamentsky** [comment]
OK, that looks better. I don't have a Mac and that's critical to testing a fix for the problem. I'd like you to try the following:
```
pip uninstall microscoper
pip install https://github.com/LeeKamentsky/microscoper.git@try-gui-script
microscoper
```
The details are pretty technical. Javabridge gets built by the Mac as a Gui application, so that it can get used by CellProfiler in a Gui context (see #136). So, what I did was make my own copy of microscoper and trick it into launching as a Gui application. Hopefully, that fixes the problem.

The problem with mixing Anaconda and the system Python has to do with libraries as well. The problem is what's often referred to as [DLL Hell](https://en.wikipedia.org/wiki/DLL_Hell) - in this case ".so hell". Somewhere back in time, people came up with the clever idea (not being ironic here) of sharing libraries between applications and only later realized that libraries have versions and the versions may not be compatible across applications. Anaconda solves this often by maintaining it's own copy of a library. This means that it's important to make sure you pick up the library (in this case, _javabridge.cpython-36m-darwin.so) that's built for Anaconda and not the one that was built for the system Python.
I feel your pain, ideally, this is something you shouldn't be burdened to learn, but such is life.

Please try this out and get back to me about whether it works for you. If it does, I will file an issue with microscoper and a pull request that fixes the problem.

**Comment by jawoll14** [comment]
Hi,
Each time I try to get the install from the link, I receive the following error.

Collecting https://github.com/LeeKamentsky/microscoper.git@try-gui-script
  HTTP error 404 while getting https://github.com/LeeKamentsky/microscoper.git@try-gui-script
  Could not install requirement https://github.com/LeeKamentsky/microscoper.git@try-gui-script because of error 404 Client Error: Not Found for url: https://github.com/LeeKamentsky/microscoper.git@try-gui-script
Could not install requirement https://github.com/LeeKamentsky/microscoper.git@try-gui-script because of HTTP error 404 Client Error: Not Found for url: https://github.com/LeeKamentsky/microscoper.git@try-gui-script for URL https://github.com/LeeKamentsky/microscoper.git@try-gui-script

**Comment by LeeKamentsky** [comment]
Sorry, can you try
```
pip install git+ https://github.com/LeeKamentsky/microscoper.git@try-gui-script
```
