### ISSUE TITLE
Javabridge error

### ISSUE THREAD

**Issue by willgdjones** [LeeKamentsky/python-javabridge#151]
Hi all - I am getting the following error when I import my javabridge package:

```
No handlers could be found for logger "javabridge.locate"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/fonz/anaconda/envs/cellprofiler/lib/python2.7/site-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/Users/fonz/anaconda/envs/cellprofiler/lib/python2.7/site-packages/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: dlopen(/Users/fonz/anaconda/envs/cellprofiler/lib/python2.7/site-packages/javabridge/_javabridge.so, 2): Symbol not found: _kCFAllocatorDefault
  Referenced from: /Users/fonz/anaconda/envs/cellprofiler/lib/python2.7/site-packages/javabridge/_javabridge.so
  Expected in: flat namespace
 in `/Users/fonz/anaconda/envs/cellprofiler/lib/python2.7/site-packages/javabridge/_javabridge.so`
```

**Comment by dschetel** [comment]
Hey,
there already exists another issue discussing this. Look at #111 
@LeeKamentsky tried to get anaconda and javabridge working and it seems to be quite intricate.

This morning I tried to use virtualenv and as of this moment, the installation of javabridge seems to work.

I used brew to install Java 8
```
brew tap caskroom/versions
brew cask install java8
```

Installation of javabridge using virtualenv
```
virtualenv venv
source venv/bin/activate
export JAVA_HOME=`/usr/libexec/java_home -v 1.8` # (set JAVA_HOME to point to Java 8)
pip install javabridge
python -c "import javabridge;javabridge.start_vm();javabridge.JClassWrapper('java.lang.System').out.printf('Hello, %s.', 'world');javabridge.kill_vm()" Hello, world.
```

Hopefully, this works for you too 👍

**Comment by LeeKamentsky** [comment]
thanks @dschetel, hope things progress more smoothly for you now.

**Comment by Fabianjr90** [comment]
dschetel's suggestion does not work for me. I still get the "Symbol not found: _kCFAllocatorDefault" error when I try to import javabridge
