### ISSUE TITLE
pip javabridge install error

### ISSUE THREAD

**Issue by kancvinu** [LeeKamentsky/python-javabridge#152]
Trying to install javabrigde on centos and getting the below error:

pip3 install --no-cache-dir javabridge==1.0.18
Collecting javabridge==1.0.18
  Downloading https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz (1.3MB)
    100% |################################| 1.3MB 576kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-twazq3g6/javabridge/setup.py", line 402, in <module>
        ext_modules=ext_modules(),
      File "/tmp/pip-install-twazq3g6/javabridge/setup.py", line 137, in ext_modules
        library_dirs = [os.path.dirname(jvm_so)]
      File "/usr/local/lib/python3.6/posixpath.py", line 156, in dirname
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-twazq3g6/javabridge/

**Comment by LeeKamentsky** [comment]
Is it possible that you haven't installed the JDK? That error is telling me that the Javabridge install script is unable to find it.

**Comment by kancvinu** [comment]
Thanks for your response. Java is installed but the JAVA_HOME path was
wrongly set. Correcting the JAVA_HOME fixed the issue.

**Comment by theodorocaliari** [comment]
Hello all, I use windows, and I have in my sistem configurated JAVA_HOME variable, but pip install javabridge not worked, it always get a error to install jdk 1.6 or newer... After a lot of failured tryes, I finnaly make it work, I maked configure the PATH variable with java directory and it works. I register this here to help others with the same problem. Cheers.

**Comment by emmenlau** [comment]
Hi Lee, hope things are fine on your side!
It would be super great if you could add this recommendation to the install docs (ideally also for CellProfiler). `python-javabridge` fails to install on a vanilla Ubuntu 16.04 and 18.04 with `openjdk-8-jdk`, `openjdk-11-jdk` and `default-jdk` packages installed. The error message is not very helpful:
```
Collecting javabridge>=1.0 (from CellProfiler==3.1.8)
  Using cached https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /opt/CellProfiler/envs/cellprofiler/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gtmtnzps/javabridge/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gtmtnzps/javabridge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-gtmtnzps/javabridge/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gtmtnzps/javabridge/setup.py", line 402, in <module>
        ext_modules=ext_modules(),
      File "/tmp/pip-install-gtmtnzps/javabridge/setup.py", line 137, in ext_modules
        library_dirs = [os.path.dirname(jvm_so)]
      File "/opt/CellProfiler/envs/cellprofiler/lib/python3.7/posixpath.py", line 156, in dirname
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
```

With some luck the user may *guess* that Java is not correctly found. Sadly, this requirement is not highlighted from the documentation at https://pythonhosted.org/javabridge/installation.html. Even when setting `JAVA_HOME` a user may be tempted to set it to the default java path on Ubuntu, i.e. something like
```
export JAVA_HOME="/usr/lib/jvm/default-java"
```
However this may default to `openjdk-11-jdk` which does not ship the required `jni.h`. The solution for me was to set
```
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
```
which then builds and works fine.

**Comment by LeeKamentsky** [comment]
There may be a jni.h file in the openjdk-11 Debian package:
https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/openjdk-11-jdk-headless_10.0.1+10-3ubuntu1_amd64.deb.html
It looks like it's put in /usr/lib/jvm/java-11-openjdk-amd64/include/jni.h
I'd appreciate a patch - I may get to looking at this at some point though.

**Comment by phinjomcent** [comment]
Hello
I'm having trouble installing javabridge in my Raspberry Pi 3B+ (Raspbian Buster).
I followed the instructions from the javabridge website and this forum stated above, but to no avail. I also followed the export command but the problem still persists. The error message is shown below and I hope this may be helpful: 

`pi@raspberrypi:~ $ export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-armhf
pi@raspberrypi:~ $ sudo pip3 install javabridge
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting javabridge
  Using cached https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-og056ij9/javabridge/setup.py", line 402, in <module>
        ext_modules=ext_modules(),
      File "/tmp/pip-install-og056ij9/javabridge/setup.py", line 137, in ext_modules
        library_dirs = [os.path.dirname(jvm_so)]
      File "/usr/lib/python3.7/posixpath.py", line 156, in dirname
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-og056ij9/javabridge/
pi@raspberrypi:~ $ 
`
Hoping for a response, Thank You!

**Comment by emmenlau** [comment]
I see that this issue is still relevant on Ubuntu 20.04...

**Comment by rayhendricks** [comment]
Trying to install CellProfiler from pip so it works with my cellpose installation.  Getting same javabridge error, I have already set java environment variable on windows 10.

**Comment by deadP1rx** [comment]
hi, i have same problem. I did set the JAVA_HOME. Although environ returns the path i still run into RuntimeError: Failed to find the Java Development Kit. Please download and install the Oracle JDK 1.6 or later. Java version: jdk-11.0.16.101-hotspot, Win

**Comment by IlioTheG** [comment]
> hi, i have same problem. I did set the JAVA_HOME. Although environ returns the path i still run into RuntimeError: Failed to find the Java Development Kit. Please download and install the Oracle JDK 1.6 or later. Java version: jdk-11.0.16.101-hotspot, Win

Solution for **Windows**

I figured out that during the installation of the package, the `python-javabridge/javabridge/locate.py` searches in the Windows Registry for the keys: 
1. 'SOFTWARE\\JavaSoft\\JDK'
2. 'SOFTWARE\\JavaSoft\\Java Development Kit'

to extract the necessary JAVA_HOME path.

<details>
  <summary>Registry screenshot</summary>
  <img src="https://github.com/user-attachments/assets/fdbddff4-9feb-4ed2-aa02-e707d59d6f41" alt="Registry screenshot" />
</details>

Although I had downloaded a JDK and set the environment variables correctly, so that java and javac where accessible from the command java was not present in the registry.

The problem solved after downloading and installing the JDK from https://adoptium.net/marketplace/ since it provides the option to edit the registry.

After that I managed to install python-javabridge by simply using `pip install python-javabridge`.

See screenshots below with the successful installation.
<details>
  <summary>CMD Screenshots</summary>
  <img src="https://github.com/user-attachments/assets/e3946745-6062-4aef-ae86-68829de26c01" alt="Successful installation" />
  <img src="https://github.com/user-attachments/assets/19cb97d1-f584-4a5a-ac7c-7f2e29550be3" alt="pip list" />
</details>
