### ISSUE TITLE
JavaBridge 1.0.18 and nosetests

### ISSUE THREAD

**Issue by BenoitFiset** [LeeKamentsky/python-javabridge#160]
Hello,

trying to follow 
```
https://pythonhosted.org/javabridge/installation.html 
and 
https://pythonhosted.org/python-bioformats/index.html#running-the-unit-tests
```
with installed javabridge-1.0.18

Installs ok but nosetests doesn't work

```
pip install python-bioformats

[SNIP]
Installing collected packages: six, python-dateutil, docutils, urllib3, jmespath, botocore, s3transfer, boto3, future, javabridge, python-bioformats
  Running setup.py install for future ... done
  Running setup.py install for javabridge ... done
  Running setup.py install for python-bioformats ... done
Successfully installed boto3-1.9.134 botocore-1.12.134 docutils-0.14 future-0.17.1 javabridge-1.0.18 jmespath-0.9.4 python-bioformats-1.5.2 python-dateutil-2.8.0 s3transfer-0.2.0 six-1.12.0 urllib3-1.24.2

```

```
python setup.py develop

[SNIP]
Installed /Users/bfiset/py3cv4/KMean/JB/javabridge-1.0.18
Processing dependencies for javabridge==1.0.18
Searching for numpy==1.16.2
Best match: numpy 1.16.2
Adding numpy 1.16.2 to easy-install.pth file
Installing f2py script to /Users/bfiset/py3cv4/KMean/bin
Installing f2py3 script to /Users/bfiset/py3cv4/KMean/bin
Installing f2py3.6 script to /Users/bfiset/py3cv4/KMean/bin

Using /Users/bfiset/py3cv4/KMean/lib/python3.6/site-packages
Finished processing dependencies for javabridge==1.0.18
```

then

```
 python setup.py nosetests

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'nosetests'
```

Ok try help

```
python setup.py --help-commands
Standard commands:
  build             build everything needed to install
  build_py          "build" pure Python modules (copy to build directory)
  build_ext         build C/C++ extensions (compile/link to build directory)
  build_clib        build C/C++ libraries used by Python extensions
  build_scripts     "build" scripts (copy and fixup #! line)
  clean             clean up temporary files from 'build' command
  install           install everything from build directory
  install_lib       install all Python modules (extensions and pure Python)
  install_headers   install C/C++ header files
  install_scripts   install scripts (Python or otherwise)
  install_data      install data files
  sdist             create a source distribution (tarball, zip file, etc.)
  register          register the distribution with the Python package index
  bdist             create a built (binary) distribution
  bdist_dumb        create a "dumb" built distribution
  bdist_rpm         create an RPM distribution
  bdist_wininst     create an executable installer for MS Windows
  check             perform some checks on the package
  upload            upload binary package to PyPI

Extra commands:
  alias             define a shortcut to invoke one or more commands
  bdist_egg         create an "egg" distribution
  develop           install package in 'development mode'
  dist_info         create a .dist-info directory
  easy_install      Find/get/install Python packages
  egg_info          create a distribution's .egg-info directory
  install_egg_info  Install an .egg-info directory for the package
  rotate            delete older distributions, keeping N newest files
  saveopts          save supplied options to setup.cfg or other config file
  setopt            set an option in setup.cfg or another config file
  test              run unit tests after in-place build
  upload_docs       Upload documentation to PyPI

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
```

There isn't any nosetests here...... and with find

```
find ./ * | grep nosetest
.//javabridge-1.0.18/.eggs/nose-1.3.7-py3.6.egg/man/man1/nosetests.1
javabridge-1.0.18/.eggs/nose-1.3.7-py3.6.egg/man/man1/nosetests.1
```

Am I missing something ?

Thanks.

**Comment by LeeKamentsky** [comment]
Probably, you need to do `pip install nose` to get nosetests.

**Comment by BenoitFiset** [comment]
Hi,

Seems to have done it.... also needed to : 

```
pip install coverage
```

Then  run python setup.py nosetests

These exceptions normal ? :

```
/Users/bfiset/py3cv4/KMean/JB/javabridge-1.0.18/javabridge/jars/libjava2cpython.jnilib
......................................Exception in thread "Thread-1" java.lang.NoSuchMethodError: copyValueOf
....................................Exception in thread "Thread-1" java.lang.NoSuchFieldError: NoSuchField
.Exception in thread "Thread-1" java.lang.NoClassDefFoundError: no/such/class

```

Full Run

```
running nosetests
running egg_info
writing javabridge.egg-info/PKG-INFO
writing dependency_links to javabridge.egg-info/dependency_links.txt
writing entry points to javabridge.egg-info/entry_points.txt
writing requirements to javabridge.egg-info/requires.txt
writing top-level names to javabridge.egg-info/top_level.txt
reading manifest file 'javabridge.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '*.pyx'
writing manifest file 'javabridge.egg-info/SOURCES.txt'
javac -source 6 -target 6 java/org/cellprofiler/runnablequeue/RunnableQueue.java
warning: [options] bootstrap class path not set in conjunction with -source 6
warning: [options] source value 6 is obsolete and will be removed in a future release
warning: [options] target value 1.6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
javac -source 6 -target 6 java/org/cellprofiler/javabridge/test/RealRect.java
warning: [options] bootstrap class path not set in conjunction with -source 6
warning: [options] source value 6 is obsolete and will be removed in a future release
warning: [options] target value 1.6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
javac -source 6 -target 6 java/org/cellprofiler/javabridge/CPython.java java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
warning: [options] bootstrap class path not set in conjunction with -source 6
warning: [options] source value 6 is obsolete and will be removed in a future release
warning: [options] target value 1.6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 warnings
copying build/lib.macosx-10.14-x86_64-3.6/javabridge/_javabridge.cpython-36m-darwin.so -> javabridge
building java2cpython library
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/bfiset/.pyenv/versions/3.6.8/include/python3.6m -Ijava -I/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/include/darwin -I/Users/bfiset/py3cv4/KMean/lib/python3.6/site-packages/numpy/core/include -I/Users/bfiset/py3cv4/KMean/include -I/Users/bfiset/.pyenv/versions/3.6.8/include/python3.6m -c java/org_cellprofiler_javabridge_CPython.c -o build/temp.macosx-10.14-x86_64-3.6/java/org_cellprofiler_javabridge_CPython.o
clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib -L/Users/bfiset/.pyenv/versions/3.6.8/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib -L/Users/bfiset/.pyenv/versions/3.6.8/lib build/temp.macosx-10.14-x86_64-3.6/java/org_cellprofiler_javabridge_CPython.o -L/Users/bfiset/.pyenv/versions/3.6.8/lib -o /Users/bfiset/py3cv4/KMean/JB/javabridge-1.0.18/javabridge/jars/libjava2cpython.jnilib
......................................Exception in thread "Thread-1" java.lang.NoSuchMethodError: copyValueOf
....................................Exception in thread "Thread-1" java.lang.NoSuchFieldError: NoSuchField
.Exception in thread "Thread-1" java.lang.NoClassDefFoundError: no/such/class
Caused by: java.lang.ClassNotFoundException: no.such.class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
..Exception in thread "Thread-1" java.lang.NoSuchFieldError: NoSuchField
.Exception in thread "Thread-1" java.lang.NoClassDefFoundError: no/such/class
Caused by: java.lang.ClassNotFoundException: no.such.class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
................................Exception in thread "Thread-1" java.util.concurrent.CancellationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
.........................Exception in thread "Thread-1" java.lang.NoSuchFieldError: NoSuchField
..Exception in thread "Thread-1" java.lang.NoSuchFieldError: NoSuchField
...............................
Name                       Stmts   Miss  Cover
----------------------------------------------
javabridge/__init__.py        29     29     0%
javabridge/jutil.py         1085    491    55%
javabridge/locate.py         151    149     1%
javabridge/noseplugin.py      44     40     9%
javabridge/wrappers.py       324     89    73%
----------------------------------------------
TOTAL                       1633    798    51%
----------------------------------------------------------------------
Ran 168 tests in 1.310s

OK

```

Is the last OK, OK ?

Thanks.

**Comment by LeeKamentsky** [comment]
In fact, those exceptions are a good sign - there are test cases to see if Javabridge can deal with Java exceptions and those exceptions are generating the messages you see. Everything looks good.

**Comment by BenoitFiset** [comment]
Cool beans !!!!

Thanks for the help.
