### ISSUE TITLE
Ubuntu18.04 install fail

### ISSUE THREAD

**Issue by ZionMi** [LeeKamentsky/python-javabridge#163]
Hi Lee, I think I  got any preparations,the java environment is OK,really don't know how to do it ,I use Ubuntu 18.04,openjdk version "11.0.2,and python 3.6.7
pip3 install javabridge
Collecting javabridge
  Using cached https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-j1e0q9qe/javabridge/setup.py", line 402, in <module>
        ext_modules=ext_modules(),
      File "/tmp/pip-build-j1e0q9qe/javabridge/setup.py", line 137, in ext_modules
        library_dirs = [os.path.dirname(jvm_so)]
      File "/usr/lib/python3.6/posixpath.py", line 156, in dirname
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j1e0q9qe/javabridge/

**Comment by kareemsoly** [comment]
Hi Lee, 

I also had the same problem on Ubuntu18.04, but it was solved after I installed Java JDK instead of JRE as you pointed out earlier on issue #82. Now it works. @ZionMi I hope that helps.
![test_bio](https://user-images.githubusercontent.com/48091160/57231704-57bddf80-701b-11e9-9f4a-142c342cb7c0.png)

Best,
Soliman

**Comment by sebi06** [comment]
Hi guys, despite trying to follow all tips I found I juts cannot install javabridge on my ubuntu 18.04. I get:

```
(base) sebi06@sebastian-tuxedo:~$ echo $JAVA_HOME
/usr/lib/jvm/java-11-oracle
(base) sebi06@sebastian-tuxedo:~$ pip install javabridge
Collecting javabridge
  Using cached https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from javabridge) (1.16.2)
Building wheels for collected packages: javabridge
  Building wheel for javabridge (setup.py) ... error
  Complete output from command /home/sebi06/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a2kwc2qu/javabridge/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-q1kutxo5 --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/noseplugin.py -> build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/__init__.py -> build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/_version.py -> build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/jutil.py -> build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/locate.py -> build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/wrappers.py -> build/lib.linux-x86_64-3.7/javabridge
  creating build/lib.linux-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_javabridge.py -> build/lib.linux-x86_64-3.7/javabridge/tests
  copying javabridge/tests/__init__.py -> build/lib.linux-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_wrappers.py -> build/lib.linux-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_cpython.py -> build/lib.linux-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_jutil.py -> build/lib.linux-x86_64-3.7/javabridge/tests
  creating build/lib.linux-x86_64-3.7/javabridge/jars
  copying javabridge/jars/rhino-1.7R4.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
  copying javabridge/jars/runnablequeue.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
  copying javabridge/jars/test.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
  copying javabridge/jars/cpython.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
  copying javabridge/jars/libjava2cpython.so -> build/lib.linux-x86_64-3.7/javabridge/jars
  running build_ext
  javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
  warning: [options] bootstrap class path not set in conjunction with -source 6
  warning: [options] source value 6 is obsolete and will be removed in a future release
  warning: [options] target value 1.6 is obsolete and will be removed in a future release
  warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
  4 warnings
  javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/test/RealRect.java
  warning: [options] bootstrap class path not set in conjunction with -source 6
  warning: [options] source value 6 is obsolete and will be removed in a future release
  warning: [options] target value 1.6 is obsolete and will be removed in a future release
  warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
  4 warnings
  javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPython.java /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
  warning: [options] bootstrap class path not set in conjunction with -source 6
  warning: [options] source value 6 is obsolete and will be removed in a future release
  warning: [options] target value 1.6 is obsolete and will be removed in a future release
  warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
  Note: /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
  Note: Recompile with -Xlint:unchecked for details.
  4 warnings
  building 'javabridge._javabridge' extension
  creating build/temp.linux-x86_64-3.7
  gcc -pthread -B /home/sebi06/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/jvm/java-11-oracle/include -I/usr/lib/jvm/java-11-oracle/include/linux -I/home/sebi06/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/sebi06/anaconda3/include/python3.7m -c _javabridge.c -o build/temp.linux-x86_64-3.7/_javabridge.o
  In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/syslimits.h:7:0,
                   from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:34,
                   from /home/sebi06/anaconda3/include/python3.7m/Python.h:11,
                   from _javabridge.c:4:
  /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:194:15: fatal error: limits.h: Datei oder Verzeichnis nicht gefunden
   #include_next <limits.h>  /* recurse down to the real one */
                 ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for javabridge
  Running setup.py clean for javabridge
Failed to build javabridge
Installing collected packages: javabridge
  Running setup.py install for javabridge ... error
    Complete output from command /home/sebi06/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a2kwc2qu/javabridge/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ydwolo09/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/noseplugin.py -> build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/__init__.py -> build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/_version.py -> build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/jutil.py -> build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/locate.py -> build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/wrappers.py -> build/lib.linux-x86_64-3.7/javabridge
    creating build/lib.linux-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_javabridge.py -> build/lib.linux-x86_64-3.7/javabridge/tests
    copying javabridge/tests/__init__.py -> build/lib.linux-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_wrappers.py -> build/lib.linux-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_cpython.py -> build/lib.linux-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_jutil.py -> build/lib.linux-x86_64-3.7/javabridge/tests
    creating build/lib.linux-x86_64-3.7/javabridge/jars
    copying javabridge/jars/rhino-1.7R4.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
    copying javabridge/jars/runnablequeue.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
    copying javabridge/jars/test.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
    copying javabridge/jars/cpython.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
    copying javabridge/jars/libjava2cpython.so -> build/lib.linux-x86_64-3.7/javabridge/jars
    running build_ext
    javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
    warning: [options] bootstrap class path not set in conjunction with -source 6
    warning: [options] source value 6 is obsolete and will be removed in a future release
    warning: [options] target value 1.6 is obsolete and will be removed in a future release
    warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    4 warnings
    javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/test/RealRect.java
    warning: [options] bootstrap class path not set in conjunction with -source 6
    warning: [options] source value 6 is obsolete and will be removed in a future release
    warning: [options] target value 1.6 is obsolete and will be removed in a future release
    warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    4 warnings
    javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPython.java /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
    warning: [options] bootstrap class path not set in conjunction with -source 6
    warning: [options] source value 6 is obsolete and will be removed in a future release
    warning: [options] target value 1.6 is obsolete and will be removed in a future release
    warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    Note: /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    4 warnings
    building 'javabridge._javabridge' extension
    creating build/temp.linux-x86_64-3.7
    gcc -pthread -B /home/sebi06/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/jvm/java-11-oracle/include -I/usr/lib/jvm/java-11-oracle/include/linux -I/home/sebi06/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/sebi06/anaconda3/include/python3.7m -c _javabridge.c -o build/temp.linux-x86_64-3.7/_javabridge.o
    In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/syslimits.h:7:0,
                     from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:34,
                     from /home/sebi06/anaconda3/include/python3.7m/Python.h:11,
                     from _javabridge.c:4:
    /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:194:15: fatal error: limits.h: Datei oder Verzeichnis nicht gefunden
     #include_next <limits.h>  /* recurse down to the real one */
                   ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/sebi06/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a2kwc2qu/javabridge/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ydwolo09/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-a2kwc2qu/javabridge/
```

**Comment by sebi06** [comment]
Now it works thanks to: https://stackoverflow.com/a/41078632
