### ISSUE TITLE
pip install error python 3.7 and openjdk-12

### ISSUE THREAD

**Issue by ocuadrosl** [LeeKamentsky/python-javabridge#166]
Installing javabridge on Arch Linux getting the following error:
_____________________________________________
Collecting javabridge
  Using cached https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jakna1v0/javabridge/setup.py", line 402, in <module>
        ext_modules=ext_modules(),
      File "/tmp/pip-install-jakna1v0/javabridge/setup.py", line 137, in ext_modules
        library_dirs = [os.path.dirname(jvm_so)]
      File "/usr/lib/python3.7/posixpath.py", line 156, in dirname
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jakna1v0/javabridge/

Thank you

**Comment by LeeKamentsky** [comment]
What version of the Java SDK do you have? Is JAVA_HOME defined as an environment variable?

**Comment by ocuadrosl** [comment]
Hi, 

java-12-openjdk, 
On arch Linux there is not JAVA_HOME variable, however, I set it, still, the installation fails.

Thank you

**Comment by LeeKamentsky** [comment]
I think the problem is most likely that we haven't added support (or yet tried) Open JDK verision 12. I'll see if I can find time to do an install with Open JDK 12 and see if I can get it to work.

**Comment by ocuadrosl** [comment]
Thank you so much, I will install using another version of open JDK,
