### ISSUE TITLE
start_vm() / kill_vm() / start_vm() -> RuntimeError: Failed to start Java VM

### ISSUE THREAD

**Issue by altendky** [LeeKamentsky/python-javabridge#171]
```bash
altendky@lt:/home/epc/t/982/tst$ git -C python-javabridge rev-parse HEAD
c7ccaed43ac7752c4ca361abb04fcb4e9ebdb069
```
```bash
altendky@lt:/home/epc/t/982/tst$ virtualenv -p ~/.pyenv/versions/3.8.0/bin/python venv380
Running virtualenv with interpreter /home/altendky/.pyenv/versions/3.8.0/bin/python
Using base prefix '/home/altendky/.pyenv/versions/3.8.0'
New python executable in /home/epc/t/982/tst/venv380/bin/python
Installing setuptools, pip, wheel...
done.
```
```bash
altendky@lt:/home/epc/t/982/tst$ venv380/bin/pip install ./python-javabridge/
Processing ./python-javabridge
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/d7/6a/3fed132c846d1e47963f30376cc041e9dd586d286d931055ad06ff65c6c7/numpy-1.17.4-cp38-cp38-manylinux1_x86_64.whl
Building wheels for collected packages: javabridge
  Building wheel for javabridge (setup.py) ... done
  Created wheel for javabridge: filename=javabridge-1.0.18.post16+gc7ccaed-cp38-cp38-linux_x86_64.whl size=1701237 sha256=df7ad2358c9eacfa883b97732ebb16badcc3bc2b0118b4c6a6860cae595950d7
  Stored in directory: /home/altendky/.cache/pip/wheels/49/d2/92/3f7cd9f9290250d06436c0dbd4fdc6db109328cd7c0c3b4c2d
Successfully built javabridge
Installing collected packages: numpy, javabridge
Successfully installed javabridge-1.0.18.post16+gc7ccaed numpy-1.17.4
```
```bash
altendky@lt:/home/epc/t/982/tst$ venv380/bin/python -c 'import javabridge; javabridge.start_vm(run_headless=True); javabridge.kill_vm(); print("starting a second time"); javabridge.start_vm(run_headless=True)'
starting a second time
Traceback (most recent call last):
  File "/home/epc/t/982/tst/venv380/lib/python3.8/site-packages/javabridge/jutil.py", line 281, in start_thread
    env = vm.create(args)
  File "_javabridge.pyx", line 654, in _javabridge.JB_VM.create
RuntimeError: Failed to create Java VM. Return code = -1
Failed to create Java VM
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/epc/t/982/tst/venv380/lib/python3.8/site-packages/javabridge/jutil.py", line 314, in start_vm
    raise RuntimeError("Failed to start Java VM")
RuntimeError: Failed to start Java VM
```
Is there another step I need to open multiple sequential VMs in a single process?  I have some test code that occasionally uses javabridge and it used to work but now doesn't.  I tested this back to Python 3.5.5 and javabridge 1.0.15 and they all did the same thing.  I probably got a Java update since it worked so I'll see how I might be able to check that.  I'll also try to find some diagnostics to pull out.  Let me know if you have any ideas of what I should be digging into.  As always, thanks.

**Comment by altendky** [comment]
Now showing the debug messages and the jdk .so.

```bash
altendky@lt:/home/epc/t/982/tst$ venv380/bin/python -c 'import javabridge; print(javabridge.jdk_so); import logging; root_logger = logging.getLogger(); logging.basicConfig(); root_logger.setLevel(logging.DEBUG); javabridge.start_vm(run_headless=True); javabridge.kill_vm(); print("starting a second time"); javabridge.start_vm()'
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
DEBUG:javabridge.jutil:Creating JVM object
DEBUG:javabridge.jutil:Signalling caller
starting a second time
DEBUG:javabridge.jutil:Creating JVM object
Traceback (most recent call last):
  File "/home/epc/t/982/tst/venv380/lib/python3.8/site-packages/javabridge/jutil.py", line 281, in start_thread
    env = vm.create(args)
  File "_javabridge.pyx", line 648, in _javabridge.JB_VM.create
RuntimeError: Failed to create Java VM. Return code = -1
ERROR:javabridge.jutil:Failed to create Java VM
DEBUG:javabridge.jutil:Signalling caller
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/epc/t/982/tst/venv380/lib/python3.8/site-packages/javabridge/jutil.py", line 314, in start_vm
    raise RuntimeError("Failed to start Java VM")
RuntimeError: Failed to start Java VM
```

**Comment by LeeKamentsky** [comment]
Sorry, Kyle, it just can't be done. It's a limitation in Java - it can only host one JVM instance per process.

**Comment by altendky** [comment]
Welp, I'm not sure what to make of this.  I swear this code was working in the past doing this.  To be clear, I am _not_ trying to make multiple instances simultaneously.  Only sequentially.  Anyways, I guess I'll just rework it to use a single and hope that there isn't too much leakage from use to use.  Thanks.
