### ISSUE TITLE
pip3 install javabridge error in Raspberry Pi

### ISSUE THREAD

**Issue by phinjomcent** [LeeKamentsky/python-javabridge#174]
Hello
I'm having trouble installing javabridge in my Raspberry Pi 3B+ (Raspbian Buster).
I followed the instructions from the javabridge website and this forum stated above, but to no avail. I also followed the export command but the problem still persists. The error message is shown below and I hope this may be helpful:

`
pi@raspberrypi:~ $ export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-armhf
pi@raspberrypi:~ $ sudo pip3 install javabridge
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting javabridge
Using cached https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-install-og056ij9/javabridge/setup.py", line 402, in
ext_modules=ext_modules(),
File "/tmp/pip-install-og056ij9/javabridge/setup.py", line 137, in ext_modules
library_dirs = [os.path.dirname(jvm_so)]
File "/usr/lib/python3.7/posixpath.py", line 156, in dirname
p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-og056ij9/javabridge/
pi@raspberrypi:~ $
`
Hoping for a response, Thank You!

**Comment by LeeKamentsky** [comment]
Hi, sorry you're having problems. I think you might be the first person to install on an ARM processor. There's some code in the setup script to look for the processor-specific directory which has the correct libjvm.so files for Java.

Could you do me a favor and give me the output on that system of:
`find /usr/lib/jvm/java-11-openjdk-armhf -name libjvm.so`

**Comment by phinjomcent** [comment]
Hello and thank your for response. The output of that command is:
`/usr/lib/jvm/java-11-openjdk-armhf/lib/server/libjvm.so`

**Comment by LeeKamentsky** [comment]
I have to admit, I'm a bit flummoxed by this one. The code to locate libjvm.so should detect that. I doubt it will help, but you might try installing the latest version:
`pip3 install https://github.com/LeeKamentsky/python-javabridge/archive/master.zip#egg=python-javabridge`
Meanwhile, I'll think about it some more and see if I can figure out why it's not working.

**Comment by phinjomcent** [comment]
Sorry for the late reply, but as I tried installing the latest version as mentioned above, the error message is still the same. :(
