### ISSUE TITLE
Could not find Java JRE compatible with x86_64 even though it's there

### ISSUE THREAD

**Issue by mathisrenier** [LeeKamentsky/python-javabridge#190]
Hello. I'm getting the following error when trying to start the jvm.

>Could not find Java JRE compatible with x86_64 architecture
DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['/Users/me/Workspace/COMP550-Final-Project/venv/lib/python3.8/site-packages/javabridge/jars/rhino-1.7R4.jar', '/Users/me/Workspace/COMP550-Final-Project/venv/lib/python3.8/site-packages/javabridge/jars/runnablequeue.jar', '/Users/me/Workspace/COMP550-Final-Project/venv/lib/python3.8/site-packages/javabridge/jars/cpython.jar', '/Users/me/Workspace/COMP550-Final-Project/venv/lib/python3.8/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/me/Workspace/COMP550-Final-Project/venv/lib/python3.8/site-packages/weka/lib/weka.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Package support enabled
ERROR:javabridge.locate:Could not find Java JRE compatible with x86_64 architecture
ERROR:javabridge.locate:Could not find Java JRE compatible with x86_64 architecture
Traceback (most recent call last):
  File "/Users/me/Workspace/COMP550-Final-Project/venv/lib/python3.8/site-packages/javabridge/jutil.py", line 114, in _find_mac_lib
    cmd = ["find", os.path.dirname(jvm_dir), "-name", library+extension]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/Users/me/Workspace/COMP550-Final-Project/venv/lib/python3.8/site-packages/javabridge/jutil.py", line 278, in start_thread
    library_path = _find_mac_lib("libjvm")
  File "/Users/me/Workspace/COMP550-Final-Project/venv/lib/python3.8/site-packages/javabridge/jutil.py", line 125, in _find_mac_lib
    (cmd, library), exc_info=1)
UnboundLocalError: local variable 'cmd' referenced before assignment
ERROR:javabridge.jutil:Failed to create Java VM
Traceback (most recent call last):
  File "/Users/me/Workspace/COMP550-Final-Project/preprocessor.py", line 8, in <module>
    jvm.start(packages=True)
  File "/Users/me/Workspace/COMP550-Final-Project/venv/lib/python3.8/site-packages/weka/core/jvm.py", line 129, in start
    javabridge.start_vm(args=args, run_headless=True, max_heap_size=max_heap_size)
  File "/Users/me/Workspace/COMP550-Final-Project/venv/lib/python3.8/site-packages/javabridge/jutil.py", line 319, in start_vm
    raise RuntimeError("Failed to start Java VM")
RuntimeError: Failed to start Java VM
>
>Process finished with exit code 1

I had to install javabridge through the github repo because the usual method didn't work. I have an ARM Mac but I'm running a x86 version of Java 8. $JAVA_HOME is set to this version of the jdk.

**Comment by mathisrenier** [comment]
The issue came from the fact that PyCharm couldn't access JAVA_HOME. Everything is working now.
