### ISSUE TITLE
javabridge._javabridge not found

### ISSUE THREAD

**Issue by PyMarc2** [LeeKamentsky/python-javabridge#193]
*CODE*
```
import javabridge
```

*ERROR*
```
Traceback (most recent call last):
  File "C:\Users\marc-\Documents\Github\FLIM-SS2021\flim_sum.py", line 1, in <module>
    import javabridge
  File "C:\Users\marc-\Documents\Github\FLIM-SS2021\venv\lib\site-packages\javabridge\__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "C:\Users\marc-\Documents\Github\FLIM-SS2021\venv\lib\site-packages\javabridge\jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ModuleNotFoundError: No module named 'javabridge._javabridge'
```

WIndow 10
installed JRE 8u291  and JDK 16.0.1
python 3.9.5

**Comment by PyMarc2** [comment]
installation was corrupted. reinstalling worked.
