### ISSUE TITLE
Exception: Error finding javahome on linux: ['bash', '-c', 'type -p java']

### ISSUE THREAD

**Issue by qq1024463088** [LeeKamentsky/python-javabridge#207]
Traceback (most recent call last):
  File "gci.py", line 873, in <module>
    augment=args.data_augment)
  File "gci.py", line 446, in build_causal_graph
    from pycausal.pycausal import pycausal as pc
  File "/environment/miniconda3/lib/python3.7/site-packages/pycausal/pycausal.py", line 32, in <module>
    import javabridge
  File "/environment/miniconda3/lib/python3.7/site-packages/javabridge/__init__.py", line 25, in <module>
    _, jdk_so = find_jre_bin_jdk_so()
  File "/environment/miniconda3/lib/python3.7/site-packages/javabridge/locate.py", line 206, in find_jre_bin_jdk_so
    java_home = find_javahome()
  File "/environment/miniconda3/lib/python3.7/site-packages/javabridge/locate.py", line 114, in find_javahome
    java_bin = get_out(["bash", "-c", "type -p java"])
  File "/environment/miniconda3/lib/python3.7/site-packages/javabridge/locate.py", line 111, in get_out
    raise Exception("Error finding javahome on linux: %s" % cmd)
Exception: Error finding javahome on linux: ['bash', '-c', 'type -p java']

**Comment by LeeKamentsky** [comment]
Hi Kim, thanks for trying Javabridge.
Can you run the following on the command line for me and send me the output?
```
type -p java
```
Also, could you try the following on the command line and send me the output?
```
java -version
```
Thanks,
Lee

**Comment by qq1024463088** [comment]
I run my program on the online studio, and it doesn't have java installed. I type java -version on the command line and it outputs "no command java". I have solve this problem but I got in some new trouble... I will send you later.
Thanks for your hospitality and your email!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeeKamentsky/python-javabridge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月11日(星期天) 凌晨4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeeKamentsky/python-javabridge] Exception: Error finding javahome on linux: ['bash', '-c', 'type -p java'] (Issue #207)





 
Hi Kim, thanks for trying Javabridge.
 Can you run the following on the command line for me and send me the output?
 type -p java  
Also, could you try the following on the command line and send me the output?
 java -version  
Thanks,
 Lee
