### ISSUE TITLE
FileNotFoundError: [WinError 206] 文件名或扩展名太长。: 'E:\\Java\\bin\\server'

### ISSUE THREAD

**Issue by Yicijiuhaobala** [LeeKamentsky/python-javabridge#213]
Traceback (most recent call last):
  File "e:/python_project/WSI/clam/pathML_preprocess/stain_deconvolution_color_ormalization.py", line 9, in <module>
    from pathml.core import HESlide
  File "E:\anaconda\envs\pytorch1_10\lib\site-packages\pathml\__init__.py", line 8, in <module>
    from . import preprocessing as pp
  File "E:\anaconda\envs\pytorch1_10\lib\site-packages\pathml\preprocessing\__init__.py", line 6, in <module>
    from .pipeline import Pipeline
  File "E:\anaconda\envs\pytorch1_10\lib\site-packages\pathml\preprocessing\pipeline.py", line 8, in <module>
    import pathml.core.tile
  File "E:\anaconda\envs\pytorch1_10\lib\site-packages\pathml\core\__init__.py", line 7, in <module>
    from .slide_backends import BioFormatsBackend, DICOMBackend, OpenSlideBackend
  File "E:\anaconda\envs\pytorch1_10\lib\site-packages\pathml\core\slide_backends.py", line 10, in <module>
    from javabridge.jutil import JavaException
  File "E:\anaconda\envs\pytorch1_10\lib\site-packages\javabridge\__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "E:\anaconda\envs\pytorch1_10\lib\site-packages\javabridge\jutil.py", line 153, in <module>
    os.add_dll_directory(_find_jvm())
  File "E:\anaconda\envs\pytorch1_10\lib\os.py", line 1105, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 206] 文件名或扩展名太长。: 'E:\\Java\\bin\\server'
how to fix this problem? i have the correct jvm file path.

**Comment by LeeKamentsky** [comment]
Hi Aohui,
I just checked in a fix, but I don't have Windows, so cannot test it. Can
you try installing javabridge like this:

pip install ***@***.***

If that works for you, I will merge to the main branch.
- Lee
(he, him, his)
