### ISSUE TITLE
Unable to install using pip

### ISSUE THREAD

**Issue by rchurt** [LeeKamentsky/python-javabridge#82]
Hello,
When I try to install javabridge using pip, it fails with the following error:

```
pip install javabridge       
Collecting javabridge
  Using cached javabridge-1.0.14.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in ./anaconda/lib/python3.5/site-packages (from javabridge)
Building wheels for collected packages: javabridge
  Running setup.py bdist_wheel for javabridge ... error
  Complete output from command /Users/Rob/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/tmpcklst7alpip-wheel- --python-tag cp35:
  Failed to run /usr/libexec/java_home, defaulting to best guess for Java
  Traceback (most recent call last):
    File "/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/javabridge/locate.py", line 45, in find_javahome
      os.path.join(os.path.dirname(path), "Libraries"),
    File "/Users/Rob/anaconda/lib/python3.5/posixpath.py", line 89, in join
      genericpath._check_arg_types('join', a, *p)
    File "/Users/Rob/anaconda/lib/python3.5/genericpath.py", line 145, in _check_arg_types
      raise TypeError("Can't mix strings and bytes in path components") from None
  TypeError: Can't mix strings and bytes in path components
  Failed to run /usr/libexec/java_home, defaulting to best guess for Java
  Traceback (most recent call last):
    File "/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/javabridge/locate.py", line 45, in find_javahome
      os.path.join(os.path.dirname(path), "Libraries"),
    File "/Users/Rob/anaconda/lib/python3.5/posixpath.py", line 89, in join
      genericpath._check_arg_types('join', a, *p)
    File "/Users/Rob/anaconda/lib/python3.5/genericpath.py", line 145, in _check_arg_types
      raise TypeError("Can't mix strings and bytes in path components") from None
  TypeError: Can't mix strings and bytes in path components
  Failed to run /usr/libexec/java_home, defaulting to best guess for Java
  Traceback (most recent call last):
    File "/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/javabridge/locate.py", line 45, in find_javahome
      os.path.join(os.path.dirname(path), "Libraries"),
    File "/Users/Rob/anaconda/lib/python3.5/posixpath.py", line 89, in join
      genericpath._check_arg_types('join', a, *p)
    File "/Users/Rob/anaconda/lib/python3.5/genericpath.py", line 145, in _check_arg_types
      raise TypeError("Can't mix strings and bytes in path components") from None
  TypeError: Can't mix strings and bytes in path components
  Failed to run /usr/libexec/java_home, defaulting to best guess for Java
  Traceback (most recent call last):
    File "/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/javabridge/locate.py", line 45, in find_javahome
      os.path.join(os.path.dirname(path), "Libraries"),
    File "/Users/Rob/anaconda/lib/python3.5/posixpath.py", line 89, in join
      genericpath._check_arg_types('join', a, *p)
    File "/Users/Rob/anaconda/lib/python3.5/genericpath.py", line 145, in _check_arg_types
      raise TypeError("Can't mix strings and bytes in path components") from None
  TypeError: Can't mix strings and bytes in path components
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.5-x86_64-3.5
  creating build/lib.macosx-10.5-x86_64-3.5/javabridge
  copying javabridge/__init__.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
  copying javabridge/_version.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
  copying javabridge/jutil.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
  copying javabridge/locate.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
  copying javabridge/noseplugin.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
  copying javabridge/wrappers.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
  creating build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
  copying javabridge/tests/__init__.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
  copying javabridge/tests/test_cpython.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
  copying javabridge/tests/test_javabridge.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
  copying javabridge/tests/test_jutil.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
  copying javabridge/tests/test_wrappers.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
  creating build/lib.macosx-10.5-x86_64-3.5/javabridge/jars
  copying javabridge/jars/cpython.jar -> build/lib.macosx-10.5-x86_64-3.5/javabridge/jars
  copying javabridge/jars/rhino-1.7R4.jar -> build/lib.macosx-10.5-x86_64-3.5/javabridge/jars
  copying javabridge/jars/runnablequeue.jar -> build/lib.macosx-10.5-x86_64-3.5/javabridge/jars
  copying javabridge/jars/test.jar -> build/lib.macosx-10.5-x86_64-3.5/javabridge/jars
  running build_ext
  javac -source 6 -target 6 /private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
  Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jre1.8.0_66.jre/Contents/Home/bin/javac" (-1)
  error: command 'javac' failed with exit status 2
  
  ----------------------------------------
  Failed building wheel for javabridge
  Running setup.py clean for javabridge
Failed to build javabridge
Installing collected packages: javabridge
  Running setup.py install for javabridge ... error
    Complete output from command /Users/Rob/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-z9l3mx7l-record/install-record.txt --single-version-externally-managed --compile:
    Failed to run /usr/libexec/java_home, defaulting to best guess for Java
    Traceback (most recent call last):
      File "/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/javabridge/locate.py", line 45, in find_javahome
        os.path.join(os.path.dirname(path), "Libraries"),
      File "/Users/Rob/anaconda/lib/python3.5/posixpath.py", line 89, in join
        genericpath._check_arg_types('join', a, *p)
      File "/Users/Rob/anaconda/lib/python3.5/genericpath.py", line 145, in _check_arg_types
        raise TypeError("Can't mix strings and bytes in path components") from None
    TypeError: Can't mix strings and bytes in path components
    Failed to run /usr/libexec/java_home, defaulting to best guess for Java
    Traceback (most recent call last):
      File "/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/javabridge/locate.py", line 45, in find_javahome
        os.path.join(os.path.dirname(path), "Libraries"),
      File "/Users/Rob/anaconda/lib/python3.5/posixpath.py", line 89, in join
        genericpath._check_arg_types('join', a, *p)
      File "/Users/Rob/anaconda/lib/python3.5/genericpath.py", line 145, in _check_arg_types
        raise TypeError("Can't mix strings and bytes in path components") from None
    TypeError: Can't mix strings and bytes in path components
    Failed to run /usr/libexec/java_home, defaulting to best guess for Java
    Traceback (most recent call last):
      File "/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/javabridge/locate.py", line 45, in find_javahome
        os.path.join(os.path.dirname(path), "Libraries"),
      File "/Users/Rob/anaconda/lib/python3.5/posixpath.py", line 89, in join
        genericpath._check_arg_types('join', a, *p)
      File "/Users/Rob/anaconda/lib/python3.5/genericpath.py", line 145, in _check_arg_types
        raise TypeError("Can't mix strings and bytes in path components") from None
    TypeError: Can't mix strings and bytes in path components
    Failed to run /usr/libexec/java_home, defaulting to best guess for Java
    Traceback (most recent call last):
      File "/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/javabridge/locate.py", line 45, in find_javahome
        os.path.join(os.path.dirname(path), "Libraries"),
      File "/Users/Rob/anaconda/lib/python3.5/posixpath.py", line 89, in join
        genericpath._check_arg_types('join', a, *p)
      File "/Users/Rob/anaconda/lib/python3.5/genericpath.py", line 145, in _check_arg_types
        raise TypeError("Can't mix strings and bytes in path components") from None
    TypeError: Can't mix strings and bytes in path components
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.5-x86_64-3.5
    creating build/lib.macosx-10.5-x86_64-3.5/javabridge
    copying javabridge/__init__.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
    copying javabridge/_version.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
    copying javabridge/jutil.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
    copying javabridge/locate.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
    copying javabridge/noseplugin.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
    copying javabridge/wrappers.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge
    creating build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
    copying javabridge/tests/__init__.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
    copying javabridge/tests/test_cpython.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
    copying javabridge/tests/test_javabridge.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
    copying javabridge/tests/test_jutil.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
    copying javabridge/tests/test_wrappers.py -> build/lib.macosx-10.5-x86_64-3.5/javabridge/tests
    creating build/lib.macosx-10.5-x86_64-3.5/javabridge/jars
    copying javabridge/jars/cpython.jar -> build/lib.macosx-10.5-x86_64-3.5/javabridge/jars
    copying javabridge/jars/rhino-1.7R4.jar -> build/lib.macosx-10.5-x86_64-3.5/javabridge/jars
    copying javabridge/jars/runnablequeue.jar -> build/lib.macosx-10.5-x86_64-3.5/javabridge/jars
    copying javabridge/jars/test.jar -> build/lib.macosx-10.5-x86_64-3.5/javabridge/jars
    running build_ext
    javac -source 6 -target 6 /private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
    Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jre1.8.0_66.jre/Contents/Home/bin/javac" (-1)
    error: command 'javac' failed with exit status 2
    
    ----------------------------------------
Command "/Users/Rob/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-z9l3mx7l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/jn/pt_9j7j52wz9jq8bzlg7bf1h0000gn/T/pip-build-9lyy16or/javabridge/
```
Any suggestions?

Thanks,
Rob

**Comment by LeeKamentsky** [comment]
It looks like Javabridge's install is finding the JRE instead of the Java SDK:

    Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jre1.8.0_66.jre/Contents/Home/bin/javac

Do you have the SDK installed? If so and you are getting the above, you might try setting JAVA_HOME to point to the SDK's root directory before doing the pip install.

**Comment by sebi06** [comment]
Hi guys, despite trying to follow all tips I found I juts cannot install javabridge on my ubuntu 18.04. I get:

```
(base) sebi06@sebastian-tuxedo:~$ echo $JAVA_HOME
/usr/lib/jvm/java-11-oracle
(base) sebi06@sebastian-tuxedo:~$ pip install javabridge
Collecting javabridge
  Using cached https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from javabridge) (1.16.2)
Building wheels for collected packages: javabridge
  Building wheel for javabridge (setup.py) ... error
  Complete output from command /home/sebi06/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a2kwc2qu/javabridge/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-q1kutxo5 --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/noseplugin.py -> build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/__init__.py -> build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/_version.py -> build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/jutil.py -> build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/locate.py -> build/lib.linux-x86_64-3.7/javabridge
  copying javabridge/wrappers.py -> build/lib.linux-x86_64-3.7/javabridge
  creating build/lib.linux-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_javabridge.py -> build/lib.linux-x86_64-3.7/javabridge/tests
  copying javabridge/tests/__init__.py -> build/lib.linux-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_wrappers.py -> build/lib.linux-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_cpython.py -> build/lib.linux-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_jutil.py -> build/lib.linux-x86_64-3.7/javabridge/tests
  creating build/lib.linux-x86_64-3.7/javabridge/jars
  copying javabridge/jars/rhino-1.7R4.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
  copying javabridge/jars/runnablequeue.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
  copying javabridge/jars/test.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
  copying javabridge/jars/cpython.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
  copying javabridge/jars/libjava2cpython.so -> build/lib.linux-x86_64-3.7/javabridge/jars
  running build_ext
  javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
  warning: [options] bootstrap class path not set in conjunction with -source 6
  warning: [options] source value 6 is obsolete and will be removed in a future release
  warning: [options] target value 1.6 is obsolete and will be removed in a future release
  warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
  4 warnings
  javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/test/RealRect.java
  warning: [options] bootstrap class path not set in conjunction with -source 6
  warning: [options] source value 6 is obsolete and will be removed in a future release
  warning: [options] target value 1.6 is obsolete and will be removed in a future release
  warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
  4 warnings
  javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPython.java /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
  warning: [options] bootstrap class path not set in conjunction with -source 6
  warning: [options] source value 6 is obsolete and will be removed in a future release
  warning: [options] target value 1.6 is obsolete and will be removed in a future release
  warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
  Note: /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
  Note: Recompile with -Xlint:unchecked for details.
  4 warnings
  building 'javabridge._javabridge' extension
  creating build/temp.linux-x86_64-3.7
  gcc -pthread -B /home/sebi06/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/jvm/java-11-oracle/include -I/usr/lib/jvm/java-11-oracle/include/linux -I/home/sebi06/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/sebi06/anaconda3/include/python3.7m -c _javabridge.c -o build/temp.linux-x86_64-3.7/_javabridge.o
  In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/syslimits.h:7:0,
                   from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:34,
                   from /home/sebi06/anaconda3/include/python3.7m/Python.h:11,
                   from _javabridge.c:4:
  /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:194:15: fatal error: limits.h: Datei oder Verzeichnis nicht gefunden
   #include_next <limits.h>  /* recurse down to the real one */
                 ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for javabridge
  Running setup.py clean for javabridge
Failed to build javabridge
Installing collected packages: javabridge
  Running setup.py install for javabridge ... error
    Complete output from command /home/sebi06/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a2kwc2qu/javabridge/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ydwolo09/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/noseplugin.py -> build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/__init__.py -> build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/_version.py -> build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/jutil.py -> build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/locate.py -> build/lib.linux-x86_64-3.7/javabridge
    copying javabridge/wrappers.py -> build/lib.linux-x86_64-3.7/javabridge
    creating build/lib.linux-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_javabridge.py -> build/lib.linux-x86_64-3.7/javabridge/tests
    copying javabridge/tests/__init__.py -> build/lib.linux-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_wrappers.py -> build/lib.linux-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_cpython.py -> build/lib.linux-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_jutil.py -> build/lib.linux-x86_64-3.7/javabridge/tests
    creating build/lib.linux-x86_64-3.7/javabridge/jars
    copying javabridge/jars/rhino-1.7R4.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
    copying javabridge/jars/runnablequeue.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
    copying javabridge/jars/test.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
    copying javabridge/jars/cpython.jar -> build/lib.linux-x86_64-3.7/javabridge/jars
    copying javabridge/jars/libjava2cpython.so -> build/lib.linux-x86_64-3.7/javabridge/jars
    running build_ext
    javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
    warning: [options] bootstrap class path not set in conjunction with -source 6
    warning: [options] source value 6 is obsolete and will be removed in a future release
    warning: [options] target value 1.6 is obsolete and will be removed in a future release
    warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    4 warnings
    javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/test/RealRect.java
    warning: [options] bootstrap class path not set in conjunction with -source 6
    warning: [options] source value 6 is obsolete and will be removed in a future release
    warning: [options] target value 1.6 is obsolete and will be removed in a future release
    warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    4 warnings
    javac -source 6 -target 6 /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPython.java /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
    warning: [options] bootstrap class path not set in conjunction with -source 6
    warning: [options] source value 6 is obsolete and will be removed in a future release
    warning: [options] target value 1.6 is obsolete and will be removed in a future release
    warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    Note: /tmp/pip-install-a2kwc2qu/javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    4 warnings
    building 'javabridge._javabridge' extension
    creating build/temp.linux-x86_64-3.7
    gcc -pthread -B /home/sebi06/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/jvm/java-11-oracle/include -I/usr/lib/jvm/java-11-oracle/include/linux -I/home/sebi06/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/sebi06/anaconda3/include/python3.7m -c _javabridge.c -o build/temp.linux-x86_64-3.7/_javabridge.o
    In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/syslimits.h:7:0,
                     from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:34,
                     from /home/sebi06/anaconda3/include/python3.7m/Python.h:11,
                     from _javabridge.c:4:
    /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:194:15: fatal error: limits.h: Datei oder Verzeichnis nicht gefunden
     #include_next <limits.h>  /* recurse down to the real one */
                   ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/sebi06/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a2kwc2qu/javabridge/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ydwolo09/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-a2kwc2qu/javabridge/
```

**Comment by sebi06** [comment]
Now it works thanks to: https://stackoverflow.com/a/41078632

**Comment by SachitNayak** [comment]
> Now it works thanks to: https://stackoverflow.com/a/41078632

I tried upgrading g++ and retrying the pip install, it still fails miserably
